/* tslint:disable */
/* eslint-disable */
/**
 * Workboard API
 * Hybrid Trello / Jira board management API
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import * as runtime from '../runtime';
import type {
  AddBoardMemberDto,
  AddCommentDto,
  CreateBoardDto,
  CreateCardDto,
  CreateColumnDto,
  MoveCardDto,
  ReorderColumnsDto,
  UpdateBoardDto,
  UpdateCardDto,
  UpdateColumnDto,
  UpdateCommentDto,
} from '../models/index';
import {
    AddBoardMemberDtoFromJSON,
    AddBoardMemberDtoToJSON,
    AddCommentDtoFromJSON,
    AddCommentDtoToJSON,
    CreateBoardDtoFromJSON,
    CreateBoardDtoToJSON,
    CreateCardDtoFromJSON,
    CreateCardDtoToJSON,
    CreateColumnDtoFromJSON,
    CreateColumnDtoToJSON,
    MoveCardDtoFromJSON,
    MoveCardDtoToJSON,
    ReorderColumnsDtoFromJSON,
    ReorderColumnsDtoToJSON,
    UpdateBoardDtoFromJSON,
    UpdateBoardDtoToJSON,
    UpdateCardDtoFromJSON,
    UpdateCardDtoToJSON,
    UpdateColumnDtoFromJSON,
    UpdateColumnDtoToJSON,
    UpdateCommentDtoFromJSON,
    UpdateCommentDtoToJSON,
} from '../models/index';

export interface BoardsControllerAddCommentRequest {
    cardId: string;
    addCommentDto: AddCommentDto;
}

export interface BoardsControllerAddMemberRequest {
    boardId: string;
    addBoardMemberDto: AddBoardMemberDto;
}

export interface BoardsControllerCreateBoardRequest {
    createBoardDto: CreateBoardDto;
}

export interface BoardsControllerCreateCardRequest {
    boardId: string;
    columnId: string;
    createCardDto: CreateCardDto;
}

export interface BoardsControllerCreateColumnRequest {
    boardId: string;
    createColumnDto: CreateColumnDto;
}

export interface BoardsControllerDeleteBoardRequest {
    boardId: string;
}

export interface BoardsControllerDeleteCardRequest {
    cardId: string;
}

export interface BoardsControllerDeleteColumnRequest {
    boardId: string;
    columnId: string;
}

export interface BoardsControllerDeleteCommentRequest {
    cardId: string;
    commentId: string;
}

export interface BoardsControllerGetBoardRequest {
    boardId: string;
}

export interface BoardsControllerMoveCardRequest {
    cardId: string;
    moveCardDto: MoveCardDto;
}

export interface BoardsControllerRemoveMemberRequest {
    boardId: string;
    memberId: string;
}

export interface BoardsControllerReorderColumnsRequest {
    boardId: string;
    reorderColumnsDto: ReorderColumnsDto;
}

export interface BoardsControllerUpdateBoardRequest {
    boardId: string;
    updateBoardDto: UpdateBoardDto;
}

export interface BoardsControllerUpdateCardRequest {
    cardId: string;
    updateCardDto: UpdateCardDto;
}

export interface BoardsControllerUpdateColumnRequest {
    boardId: string;
    columnId: string;
    updateColumnDto: UpdateColumnDto;
}

export interface BoardsControllerUpdateCommentRequest {
    cardId: string;
    commentId: string;
    updateCommentDto: UpdateCommentDto;
}

/**
 * BoardsApi - interface
 * 
 * @export
 * @interface BoardsApiInterface
 */
export interface BoardsApiInterface {
    /**
     * 
     * @param {string} cardId 
     * @param {AddCommentDto} addCommentDto 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof BoardsApiInterface
     */
    boardsControllerAddCommentRaw(requestParameters: BoardsControllerAddCommentRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<void>>;

    /**
     */
    boardsControllerAddComment(requestParameters: BoardsControllerAddCommentRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<void>;

    /**
     * 
     * @param {string} boardId 
     * @param {AddBoardMemberDto} addBoardMemberDto 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof BoardsApiInterface
     */
    boardsControllerAddMemberRaw(requestParameters: BoardsControllerAddMemberRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<void>>;

    /**
     */
    boardsControllerAddMember(requestParameters: BoardsControllerAddMemberRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<void>;

    /**
     * 
     * @param {CreateBoardDto} createBoardDto 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof BoardsApiInterface
     */
    boardsControllerCreateBoardRaw(requestParameters: BoardsControllerCreateBoardRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<void>>;

    /**
     */
    boardsControllerCreateBoard(requestParameters: BoardsControllerCreateBoardRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<void>;

    /**
     * 
     * @param {string} boardId 
     * @param {string} columnId 
     * @param {CreateCardDto} createCardDto 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof BoardsApiInterface
     */
    boardsControllerCreateCardRaw(requestParameters: BoardsControllerCreateCardRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<void>>;

    /**
     */
    boardsControllerCreateCard(requestParameters: BoardsControllerCreateCardRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<void>;

    /**
     * 
     * @param {string} boardId 
     * @param {CreateColumnDto} createColumnDto 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof BoardsApiInterface
     */
    boardsControllerCreateColumnRaw(requestParameters: BoardsControllerCreateColumnRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<void>>;

    /**
     */
    boardsControllerCreateColumn(requestParameters: BoardsControllerCreateColumnRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<void>;

    /**
     * 
     * @param {string} boardId 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof BoardsApiInterface
     */
    boardsControllerDeleteBoardRaw(requestParameters: BoardsControllerDeleteBoardRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<void>>;

    /**
     */
    boardsControllerDeleteBoard(requestParameters: BoardsControllerDeleteBoardRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<void>;

    /**
     * 
     * @param {string} cardId 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof BoardsApiInterface
     */
    boardsControllerDeleteCardRaw(requestParameters: BoardsControllerDeleteCardRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<void>>;

    /**
     */
    boardsControllerDeleteCard(requestParameters: BoardsControllerDeleteCardRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<void>;

    /**
     * 
     * @param {string} boardId 
     * @param {string} columnId 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof BoardsApiInterface
     */
    boardsControllerDeleteColumnRaw(requestParameters: BoardsControllerDeleteColumnRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<void>>;

    /**
     */
    boardsControllerDeleteColumn(requestParameters: BoardsControllerDeleteColumnRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<void>;

    /**
     * 
     * @param {string} cardId 
     * @param {string} commentId 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof BoardsApiInterface
     */
    boardsControllerDeleteCommentRaw(requestParameters: BoardsControllerDeleteCommentRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<void>>;

    /**
     */
    boardsControllerDeleteComment(requestParameters: BoardsControllerDeleteCommentRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<void>;

    /**
     * 
     * @param {string} boardId 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof BoardsApiInterface
     */
    boardsControllerGetBoardRaw(requestParameters: BoardsControllerGetBoardRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<void>>;

    /**
     */
    boardsControllerGetBoard(requestParameters: BoardsControllerGetBoardRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<void>;

    /**
     * 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof BoardsApiInterface
     */
    boardsControllerListBoardsRaw(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<void>>;

    /**
     */
    boardsControllerListBoards(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<void>;

    /**
     * 
     * @param {string} cardId 
     * @param {MoveCardDto} moveCardDto 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof BoardsApiInterface
     */
    boardsControllerMoveCardRaw(requestParameters: BoardsControllerMoveCardRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<void>>;

    /**
     */
    boardsControllerMoveCard(requestParameters: BoardsControllerMoveCardRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<void>;

    /**
     * 
     * @param {string} boardId 
     * @param {string} memberId 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof BoardsApiInterface
     */
    boardsControllerRemoveMemberRaw(requestParameters: BoardsControllerRemoveMemberRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<void>>;

    /**
     */
    boardsControllerRemoveMember(requestParameters: BoardsControllerRemoveMemberRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<void>;

    /**
     * 
     * @param {string} boardId 
     * @param {ReorderColumnsDto} reorderColumnsDto 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof BoardsApiInterface
     */
    boardsControllerReorderColumnsRaw(requestParameters: BoardsControllerReorderColumnsRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<void>>;

    /**
     */
    boardsControllerReorderColumns(requestParameters: BoardsControllerReorderColumnsRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<void>;

    /**
     * 
     * @param {string} boardId 
     * @param {UpdateBoardDto} updateBoardDto 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof BoardsApiInterface
     */
    boardsControllerUpdateBoardRaw(requestParameters: BoardsControllerUpdateBoardRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<void>>;

    /**
     */
    boardsControllerUpdateBoard(requestParameters: BoardsControllerUpdateBoardRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<void>;

    /**
     * 
     * @param {string} cardId 
     * @param {UpdateCardDto} updateCardDto 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof BoardsApiInterface
     */
    boardsControllerUpdateCardRaw(requestParameters: BoardsControllerUpdateCardRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<void>>;

    /**
     */
    boardsControllerUpdateCard(requestParameters: BoardsControllerUpdateCardRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<void>;

    /**
     * 
     * @param {string} boardId 
     * @param {string} columnId 
     * @param {UpdateColumnDto} updateColumnDto 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof BoardsApiInterface
     */
    boardsControllerUpdateColumnRaw(requestParameters: BoardsControllerUpdateColumnRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<void>>;

    /**
     */
    boardsControllerUpdateColumn(requestParameters: BoardsControllerUpdateColumnRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<void>;

    /**
     * 
     * @param {string} cardId 
     * @param {string} commentId 
     * @param {UpdateCommentDto} updateCommentDto 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof BoardsApiInterface
     */
    boardsControllerUpdateCommentRaw(requestParameters: BoardsControllerUpdateCommentRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<void>>;

    /**
     */
    boardsControllerUpdateComment(requestParameters: BoardsControllerUpdateCommentRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<void>;

}

/**
 * 
 */
export class BoardsApi extends runtime.BaseAPI implements BoardsApiInterface {

    /**
     */
    async boardsControllerAddCommentRaw(requestParameters: BoardsControllerAddCommentRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<void>> {
        if (requestParameters['cardId'] == null) {
            throw new runtime.RequiredError(
                'cardId',
                'Required parameter "cardId" was null or undefined when calling boardsControllerAddComment().'
            );
        }

        if (requestParameters['addCommentDto'] == null) {
            throw new runtime.RequiredError(
                'addCommentDto',
                'Required parameter "addCommentDto" was null or undefined when calling boardsControllerAddComment().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("bearer", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/api/boards/cards/{cardId}/comments`;
        urlPath = urlPath.replace(`{${"cardId"}}`, encodeURIComponent(String(requestParameters['cardId'])));

        const response = await this.request({
            path: urlPath,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: AddCommentDtoToJSON(requestParameters['addCommentDto']),
        }, initOverrides);

        return new runtime.VoidApiResponse(response);
    }

    /**
     */
    async boardsControllerAddComment(requestParameters: BoardsControllerAddCommentRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<void> {
        await this.boardsControllerAddCommentRaw(requestParameters, initOverrides);
    }

    /**
     */
    async boardsControllerAddMemberRaw(requestParameters: BoardsControllerAddMemberRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<void>> {
        if (requestParameters['boardId'] == null) {
            throw new runtime.RequiredError(
                'boardId',
                'Required parameter "boardId" was null or undefined when calling boardsControllerAddMember().'
            );
        }

        if (requestParameters['addBoardMemberDto'] == null) {
            throw new runtime.RequiredError(
                'addBoardMemberDto',
                'Required parameter "addBoardMemberDto" was null or undefined when calling boardsControllerAddMember().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("bearer", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/api/boards/{boardId}/members`;
        urlPath = urlPath.replace(`{${"boardId"}}`, encodeURIComponent(String(requestParameters['boardId'])));

        const response = await this.request({
            path: urlPath,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: AddBoardMemberDtoToJSON(requestParameters['addBoardMemberDto']),
        }, initOverrides);

        return new runtime.VoidApiResponse(response);
    }

    /**
     */
    async boardsControllerAddMember(requestParameters: BoardsControllerAddMemberRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<void> {
        await this.boardsControllerAddMemberRaw(requestParameters, initOverrides);
    }

    /**
     */
    async boardsControllerCreateBoardRaw(requestParameters: BoardsControllerCreateBoardRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<void>> {
        if (requestParameters['createBoardDto'] == null) {
            throw new runtime.RequiredError(
                'createBoardDto',
                'Required parameter "createBoardDto" was null or undefined when calling boardsControllerCreateBoard().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("bearer", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/api/boards`;

        const response = await this.request({
            path: urlPath,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: CreateBoardDtoToJSON(requestParameters['createBoardDto']),
        }, initOverrides);

        return new runtime.VoidApiResponse(response);
    }

    /**
     */
    async boardsControllerCreateBoard(requestParameters: BoardsControllerCreateBoardRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<void> {
        await this.boardsControllerCreateBoardRaw(requestParameters, initOverrides);
    }

    /**
     */
    async boardsControllerCreateCardRaw(requestParameters: BoardsControllerCreateCardRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<void>> {
        if (requestParameters['boardId'] == null) {
            throw new runtime.RequiredError(
                'boardId',
                'Required parameter "boardId" was null or undefined when calling boardsControllerCreateCard().'
            );
        }

        if (requestParameters['columnId'] == null) {
            throw new runtime.RequiredError(
                'columnId',
                'Required parameter "columnId" was null or undefined when calling boardsControllerCreateCard().'
            );
        }

        if (requestParameters['createCardDto'] == null) {
            throw new runtime.RequiredError(
                'createCardDto',
                'Required parameter "createCardDto" was null or undefined when calling boardsControllerCreateCard().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("bearer", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/api/boards/{boardId}/columns/{columnId}/cards`;
        urlPath = urlPath.replace(`{${"boardId"}}`, encodeURIComponent(String(requestParameters['boardId'])));
        urlPath = urlPath.replace(`{${"columnId"}}`, encodeURIComponent(String(requestParameters['columnId'])));

        const response = await this.request({
            path: urlPath,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: CreateCardDtoToJSON(requestParameters['createCardDto']),
        }, initOverrides);

        return new runtime.VoidApiResponse(response);
    }

    /**
     */
    async boardsControllerCreateCard(requestParameters: BoardsControllerCreateCardRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<void> {
        await this.boardsControllerCreateCardRaw(requestParameters, initOverrides);
    }

    /**
     */
    async boardsControllerCreateColumnRaw(requestParameters: BoardsControllerCreateColumnRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<void>> {
        if (requestParameters['boardId'] == null) {
            throw new runtime.RequiredError(
                'boardId',
                'Required parameter "boardId" was null or undefined when calling boardsControllerCreateColumn().'
            );
        }

        if (requestParameters['createColumnDto'] == null) {
            throw new runtime.RequiredError(
                'createColumnDto',
                'Required parameter "createColumnDto" was null or undefined when calling boardsControllerCreateColumn().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("bearer", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/api/boards/{boardId}/columns`;
        urlPath = urlPath.replace(`{${"boardId"}}`, encodeURIComponent(String(requestParameters['boardId'])));

        const response = await this.request({
            path: urlPath,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: CreateColumnDtoToJSON(requestParameters['createColumnDto']),
        }, initOverrides);

        return new runtime.VoidApiResponse(response);
    }

    /**
     */
    async boardsControllerCreateColumn(requestParameters: BoardsControllerCreateColumnRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<void> {
        await this.boardsControllerCreateColumnRaw(requestParameters, initOverrides);
    }

    /**
     */
    async boardsControllerDeleteBoardRaw(requestParameters: BoardsControllerDeleteBoardRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<void>> {
        if (requestParameters['boardId'] == null) {
            throw new runtime.RequiredError(
                'boardId',
                'Required parameter "boardId" was null or undefined when calling boardsControllerDeleteBoard().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("bearer", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/api/boards/{boardId}`;
        urlPath = urlPath.replace(`{${"boardId"}}`, encodeURIComponent(String(requestParameters['boardId'])));

        const response = await this.request({
            path: urlPath,
            method: 'DELETE',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.VoidApiResponse(response);
    }

    /**
     */
    async boardsControllerDeleteBoard(requestParameters: BoardsControllerDeleteBoardRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<void> {
        await this.boardsControllerDeleteBoardRaw(requestParameters, initOverrides);
    }

    /**
     */
    async boardsControllerDeleteCardRaw(requestParameters: BoardsControllerDeleteCardRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<void>> {
        if (requestParameters['cardId'] == null) {
            throw new runtime.RequiredError(
                'cardId',
                'Required parameter "cardId" was null or undefined when calling boardsControllerDeleteCard().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("bearer", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/api/boards/cards/{cardId}`;
        urlPath = urlPath.replace(`{${"cardId"}}`, encodeURIComponent(String(requestParameters['cardId'])));

        const response = await this.request({
            path: urlPath,
            method: 'DELETE',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.VoidApiResponse(response);
    }

    /**
     */
    async boardsControllerDeleteCard(requestParameters: BoardsControllerDeleteCardRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<void> {
        await this.boardsControllerDeleteCardRaw(requestParameters, initOverrides);
    }

    /**
     */
    async boardsControllerDeleteColumnRaw(requestParameters: BoardsControllerDeleteColumnRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<void>> {
        if (requestParameters['boardId'] == null) {
            throw new runtime.RequiredError(
                'boardId',
                'Required parameter "boardId" was null or undefined when calling boardsControllerDeleteColumn().'
            );
        }

        if (requestParameters['columnId'] == null) {
            throw new runtime.RequiredError(
                'columnId',
                'Required parameter "columnId" was null or undefined when calling boardsControllerDeleteColumn().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("bearer", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/api/boards/{boardId}/columns/{columnId}`;
        urlPath = urlPath.replace(`{${"boardId"}}`, encodeURIComponent(String(requestParameters['boardId'])));
        urlPath = urlPath.replace(`{${"columnId"}}`, encodeURIComponent(String(requestParameters['columnId'])));

        const response = await this.request({
            path: urlPath,
            method: 'DELETE',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.VoidApiResponse(response);
    }

    /**
     */
    async boardsControllerDeleteColumn(requestParameters: BoardsControllerDeleteColumnRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<void> {
        await this.boardsControllerDeleteColumnRaw(requestParameters, initOverrides);
    }

    /**
     */
    async boardsControllerDeleteCommentRaw(requestParameters: BoardsControllerDeleteCommentRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<void>> {
        if (requestParameters['cardId'] == null) {
            throw new runtime.RequiredError(
                'cardId',
                'Required parameter "cardId" was null or undefined when calling boardsControllerDeleteComment().'
            );
        }

        if (requestParameters['commentId'] == null) {
            throw new runtime.RequiredError(
                'commentId',
                'Required parameter "commentId" was null or undefined when calling boardsControllerDeleteComment().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("bearer", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/api/boards/cards/{cardId}/comments/{commentId}`;
        urlPath = urlPath.replace(`{${"cardId"}}`, encodeURIComponent(String(requestParameters['cardId'])));
        urlPath = urlPath.replace(`{${"commentId"}}`, encodeURIComponent(String(requestParameters['commentId'])));

        const response = await this.request({
            path: urlPath,
            method: 'DELETE',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.VoidApiResponse(response);
    }

    /**
     */
    async boardsControllerDeleteComment(requestParameters: BoardsControllerDeleteCommentRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<void> {
        await this.boardsControllerDeleteCommentRaw(requestParameters, initOverrides);
    }

    /**
     */
    async boardsControllerGetBoardRaw(requestParameters: BoardsControllerGetBoardRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<void>> {
        if (requestParameters['boardId'] == null) {
            throw new runtime.RequiredError(
                'boardId',
                'Required parameter "boardId" was null or undefined when calling boardsControllerGetBoard().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("bearer", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/api/boards/{boardId}`;
        urlPath = urlPath.replace(`{${"boardId"}}`, encodeURIComponent(String(requestParameters['boardId'])));

        const response = await this.request({
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.VoidApiResponse(response);
    }

    /**
     */
    async boardsControllerGetBoard(requestParameters: BoardsControllerGetBoardRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<void> {
        await this.boardsControllerGetBoardRaw(requestParameters, initOverrides);
    }

    /**
     */
    async boardsControllerListBoardsRaw(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<void>> {
        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("bearer", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/api/boards`;

        const response = await this.request({
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.VoidApiResponse(response);
    }

    /**
     */
    async boardsControllerListBoards(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<void> {
        await this.boardsControllerListBoardsRaw(initOverrides);
    }

    /**
     */
    async boardsControllerMoveCardRaw(requestParameters: BoardsControllerMoveCardRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<void>> {
        if (requestParameters['cardId'] == null) {
            throw new runtime.RequiredError(
                'cardId',
                'Required parameter "cardId" was null or undefined when calling boardsControllerMoveCard().'
            );
        }

        if (requestParameters['moveCardDto'] == null) {
            throw new runtime.RequiredError(
                'moveCardDto',
                'Required parameter "moveCardDto" was null or undefined when calling boardsControllerMoveCard().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("bearer", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/api/boards/cards/{cardId}/move`;
        urlPath = urlPath.replace(`{${"cardId"}}`, encodeURIComponent(String(requestParameters['cardId'])));

        const response = await this.request({
            path: urlPath,
            method: 'PATCH',
            headers: headerParameters,
            query: queryParameters,
            body: MoveCardDtoToJSON(requestParameters['moveCardDto']),
        }, initOverrides);

        return new runtime.VoidApiResponse(response);
    }

    /**
     */
    async boardsControllerMoveCard(requestParameters: BoardsControllerMoveCardRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<void> {
        await this.boardsControllerMoveCardRaw(requestParameters, initOverrides);
    }

    /**
     */
    async boardsControllerRemoveMemberRaw(requestParameters: BoardsControllerRemoveMemberRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<void>> {
        if (requestParameters['boardId'] == null) {
            throw new runtime.RequiredError(
                'boardId',
                'Required parameter "boardId" was null or undefined when calling boardsControllerRemoveMember().'
            );
        }

        if (requestParameters['memberId'] == null) {
            throw new runtime.RequiredError(
                'memberId',
                'Required parameter "memberId" was null or undefined when calling boardsControllerRemoveMember().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("bearer", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/api/boards/{boardId}/members/{memberId}`;
        urlPath = urlPath.replace(`{${"boardId"}}`, encodeURIComponent(String(requestParameters['boardId'])));
        urlPath = urlPath.replace(`{${"memberId"}}`, encodeURIComponent(String(requestParameters['memberId'])));

        const response = await this.request({
            path: urlPath,
            method: 'DELETE',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.VoidApiResponse(response);
    }

    /**
     */
    async boardsControllerRemoveMember(requestParameters: BoardsControllerRemoveMemberRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<void> {
        await this.boardsControllerRemoveMemberRaw(requestParameters, initOverrides);
    }

    /**
     */
    async boardsControllerReorderColumnsRaw(requestParameters: BoardsControllerReorderColumnsRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<void>> {
        if (requestParameters['boardId'] == null) {
            throw new runtime.RequiredError(
                'boardId',
                'Required parameter "boardId" was null or undefined when calling boardsControllerReorderColumns().'
            );
        }

        if (requestParameters['reorderColumnsDto'] == null) {
            throw new runtime.RequiredError(
                'reorderColumnsDto',
                'Required parameter "reorderColumnsDto" was null or undefined when calling boardsControllerReorderColumns().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("bearer", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/api/boards/{boardId}/columns/reorder`;
        urlPath = urlPath.replace(`{${"boardId"}}`, encodeURIComponent(String(requestParameters['boardId'])));

        const response = await this.request({
            path: urlPath,
            method: 'PATCH',
            headers: headerParameters,
            query: queryParameters,
            body: ReorderColumnsDtoToJSON(requestParameters['reorderColumnsDto']),
        }, initOverrides);

        return new runtime.VoidApiResponse(response);
    }

    /**
     */
    async boardsControllerReorderColumns(requestParameters: BoardsControllerReorderColumnsRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<void> {
        await this.boardsControllerReorderColumnsRaw(requestParameters, initOverrides);
    }

    /**
     */
    async boardsControllerUpdateBoardRaw(requestParameters: BoardsControllerUpdateBoardRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<void>> {
        if (requestParameters['boardId'] == null) {
            throw new runtime.RequiredError(
                'boardId',
                'Required parameter "boardId" was null or undefined when calling boardsControllerUpdateBoard().'
            );
        }

        if (requestParameters['updateBoardDto'] == null) {
            throw new runtime.RequiredError(
                'updateBoardDto',
                'Required parameter "updateBoardDto" was null or undefined when calling boardsControllerUpdateBoard().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("bearer", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/api/boards/{boardId}`;
        urlPath = urlPath.replace(`{${"boardId"}}`, encodeURIComponent(String(requestParameters['boardId'])));

        const response = await this.request({
            path: urlPath,
            method: 'PATCH',
            headers: headerParameters,
            query: queryParameters,
            body: UpdateBoardDtoToJSON(requestParameters['updateBoardDto']),
        }, initOverrides);

        return new runtime.VoidApiResponse(response);
    }

    /**
     */
    async boardsControllerUpdateBoard(requestParameters: BoardsControllerUpdateBoardRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<void> {
        await this.boardsControllerUpdateBoardRaw(requestParameters, initOverrides);
    }

    /**
     */
    async boardsControllerUpdateCardRaw(requestParameters: BoardsControllerUpdateCardRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<void>> {
        if (requestParameters['cardId'] == null) {
            throw new runtime.RequiredError(
                'cardId',
                'Required parameter "cardId" was null or undefined when calling boardsControllerUpdateCard().'
            );
        }

        if (requestParameters['updateCardDto'] == null) {
            throw new runtime.RequiredError(
                'updateCardDto',
                'Required parameter "updateCardDto" was null or undefined when calling boardsControllerUpdateCard().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("bearer", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/api/boards/cards/{cardId}`;
        urlPath = urlPath.replace(`{${"cardId"}}`, encodeURIComponent(String(requestParameters['cardId'])));

        const response = await this.request({
            path: urlPath,
            method: 'PATCH',
            headers: headerParameters,
            query: queryParameters,
            body: UpdateCardDtoToJSON(requestParameters['updateCardDto']),
        }, initOverrides);

        return new runtime.VoidApiResponse(response);
    }

    /**
     */
    async boardsControllerUpdateCard(requestParameters: BoardsControllerUpdateCardRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<void> {
        await this.boardsControllerUpdateCardRaw(requestParameters, initOverrides);
    }

    /**
     */
    async boardsControllerUpdateColumnRaw(requestParameters: BoardsControllerUpdateColumnRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<void>> {
        if (requestParameters['boardId'] == null) {
            throw new runtime.RequiredError(
                'boardId',
                'Required parameter "boardId" was null or undefined when calling boardsControllerUpdateColumn().'
            );
        }

        if (requestParameters['columnId'] == null) {
            throw new runtime.RequiredError(
                'columnId',
                'Required parameter "columnId" was null or undefined when calling boardsControllerUpdateColumn().'
            );
        }

        if (requestParameters['updateColumnDto'] == null) {
            throw new runtime.RequiredError(
                'updateColumnDto',
                'Required parameter "updateColumnDto" was null or undefined when calling boardsControllerUpdateColumn().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("bearer", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/api/boards/{boardId}/columns/{columnId}`;
        urlPath = urlPath.replace(`{${"boardId"}}`, encodeURIComponent(String(requestParameters['boardId'])));
        urlPath = urlPath.replace(`{${"columnId"}}`, encodeURIComponent(String(requestParameters['columnId'])));

        const response = await this.request({
            path: urlPath,
            method: 'PATCH',
            headers: headerParameters,
            query: queryParameters,
            body: UpdateColumnDtoToJSON(requestParameters['updateColumnDto']),
        }, initOverrides);

        return new runtime.VoidApiResponse(response);
    }

    /**
     */
    async boardsControllerUpdateColumn(requestParameters: BoardsControllerUpdateColumnRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<void> {
        await this.boardsControllerUpdateColumnRaw(requestParameters, initOverrides);
    }

    /**
     */
    async boardsControllerUpdateCommentRaw(requestParameters: BoardsControllerUpdateCommentRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<void>> {
        if (requestParameters['cardId'] == null) {
            throw new runtime.RequiredError(
                'cardId',
                'Required parameter "cardId" was null or undefined when calling boardsControllerUpdateComment().'
            );
        }

        if (requestParameters['commentId'] == null) {
            throw new runtime.RequiredError(
                'commentId',
                'Required parameter "commentId" was null or undefined when calling boardsControllerUpdateComment().'
            );
        }

        if (requestParameters['updateCommentDto'] == null) {
            throw new runtime.RequiredError(
                'updateCommentDto',
                'Required parameter "updateCommentDto" was null or undefined when calling boardsControllerUpdateComment().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("bearer", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/api/boards/cards/{cardId}/comments/{commentId}`;
        urlPath = urlPath.replace(`{${"cardId"}}`, encodeURIComponent(String(requestParameters['cardId'])));
        urlPath = urlPath.replace(`{${"commentId"}}`, encodeURIComponent(String(requestParameters['commentId'])));

        const response = await this.request({
            path: urlPath,
            method: 'PATCH',
            headers: headerParameters,
            query: queryParameters,
            body: UpdateCommentDtoToJSON(requestParameters['updateCommentDto']),
        }, initOverrides);

        return new runtime.VoidApiResponse(response);
    }

    /**
     */
    async boardsControllerUpdateComment(requestParameters: BoardsControllerUpdateCommentRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<void> {
        await this.boardsControllerUpdateCommentRaw(requestParameters, initOverrides);
    }

}
