/* tslint:disable */
/* eslint-disable */
/**
 * Workboard API
 * Hybrid Trello / Jira board management API
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface AddAttachmentDto
 */
export interface AddAttachmentDto {
    /**
     * 
     * @type {string}
     * @memberof AddAttachmentDto
     */
    name: string;
    /**
     * 
     * @type {string}
     * @memberof AddAttachmentDto
     */
    url: string;
    /**
     * 
     * @type {string}
     * @memberof AddAttachmentDto
     */
    mimeType?: string;
}

/**
 * Check if a given object implements the AddAttachmentDto interface.
 */
export function instanceOfAddAttachmentDto(value: object): value is AddAttachmentDto {
    if (!('name' in value) || value['name'] === undefined) return false;
    if (!('url' in value) || value['url'] === undefined) return false;
    return true;
}

export function AddAttachmentDtoFromJSON(json: any): AddAttachmentDto {
    return AddAttachmentDtoFromJSONTyped(json, false);
}

export function AddAttachmentDtoFromJSONTyped(json: any, ignoreDiscriminator: boolean): AddAttachmentDto {
    if (json == null) {
        return json;
    }
    return {
        
        'name': json['name'],
        'url': json['url'],
        'mimeType': json['mimeType'] == null ? undefined : json['mimeType'],
    };
}

export function AddAttachmentDtoToJSON(json: any): AddAttachmentDto {
    return AddAttachmentDtoToJSONTyped(json, false);
}

export function AddAttachmentDtoToJSONTyped(value?: AddAttachmentDto | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'name': value['name'],
        'url': value['url'],
        'mimeType': value['mimeType'],
    };
}

