/* tslint:disable */
/* eslint-disable */
/**
 * Workboard API
 * Hybrid Trello / Jira board management API
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface AddCommentDto
 */
export interface AddCommentDto {
    /**
     * 
     * @type {string}
     * @memberof AddCommentDto
     */
    content: string;
}

/**
 * Check if a given object implements the AddCommentDto interface.
 */
export function instanceOfAddCommentDto(value: object): value is AddCommentDto {
    if (!('content' in value) || value['content'] === undefined) return false;
    return true;
}

export function AddCommentDtoFromJSON(json: any): AddCommentDto {
    return AddCommentDtoFromJSONTyped(json, false);
}

export function AddCommentDtoFromJSONTyped(json: any, ignoreDiscriminator: boolean): AddCommentDto {
    if (json == null) {
        return json;
    }
    return {
        
        'content': json['content'],
    };
}

export function AddCommentDtoToJSON(json: any): AddCommentDto {
    return AddCommentDtoToJSONTyped(json, false);
}

export function AddCommentDtoToJSONTyped(value?: AddCommentDto | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'content': value['content'],
    };
}

