/* tslint:disable */
/* eslint-disable */
/**
 * Workboard API
 * Hybrid Trello / Jira board management API
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface CreateChecklistItemDto
 */
export interface CreateChecklistItemDto {
    /**
     * 
     * @type {string}
     * @memberof CreateChecklistItemDto
     */
    content: string;
}

/**
 * Check if a given object implements the CreateChecklistItemDto interface.
 */
export function instanceOfCreateChecklistItemDto(value: object): value is CreateChecklistItemDto {
    if (!('content' in value) || value['content'] === undefined) return false;
    return true;
}

export function CreateChecklistItemDtoFromJSON(json: any): CreateChecklistItemDto {
    return CreateChecklistItemDtoFromJSONTyped(json, false);
}

export function CreateChecklistItemDtoFromJSONTyped(json: any, ignoreDiscriminator: boolean): CreateChecklistItemDto {
    if (json == null) {
        return json;
    }
    return {
        
        'content': json['content'],
    };
}

export function CreateChecklistItemDtoToJSON(json: any): CreateChecklistItemDto {
    return CreateChecklistItemDtoToJSONTyped(json, false);
}

export function CreateChecklistItemDtoToJSONTyped(value?: CreateChecklistItemDto | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'content': value['content'],
    };
}

