/* tslint:disable */
/* eslint-disable */
/**
 * Workboard API
 * Hybrid Trello / Jira board management API
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface CreateCardDto
 */
export interface CreateCardDto {
    /**
     * 
     * @type {string}
     * @memberof CreateCardDto
     */
    title: string;
    /**
     * 
     * @type {string}
     * @memberof CreateCardDto
     */
    description?: string;
    /**
     * 
     * @type {string}
     * @memberof CreateCardDto
     */
    priority?: CreateCardDtoPriorityEnum;
    /**
     * 
     * @type {string}
     * @memberof CreateCardDto
     */
    type?: CreateCardDtoTypeEnum;
    /**
     * 
     * @type {Date}
     * @memberof CreateCardDto
     */
    dueDate?: Date;
    /**
     * 
     * @type {number}
     * @memberof CreateCardDto
     */
    storyPoints?: number;
    /**
     * 
     * @type {string}
     * @memberof CreateCardDto
     */
    assigneeId?: string;
    /**
     * 
     * @type {string}
     * @memberof CreateCardDto
     */
    reporterId?: string;
    /**
     * Associated label identifiers
     * @type {Array<string>}
     * @memberof CreateCardDto
     */
    labelIds?: Array<string>;
}


/**
 * @export
 */
export const CreateCardDtoPriorityEnum = {
    Low: 'LOW',
    Medium: 'MEDIUM',
    High: 'HIGH',
    Critical: 'CRITICAL'
} as const;
export type CreateCardDtoPriorityEnum = typeof CreateCardDtoPriorityEnum[keyof typeof CreateCardDtoPriorityEnum];

/**
 * @export
 */
export const CreateCardDtoTypeEnum = {
    Task: 'TASK',
    Bug: 'BUG',
    Story: 'STORY',
    Epic: 'EPIC'
} as const;
export type CreateCardDtoTypeEnum = typeof CreateCardDtoTypeEnum[keyof typeof CreateCardDtoTypeEnum];


/**
 * Check if a given object implements the CreateCardDto interface.
 */
export function instanceOfCreateCardDto(value: object): value is CreateCardDto {
    if (!('title' in value) || value['title'] === undefined) return false;
    return true;
}

export function CreateCardDtoFromJSON(json: any): CreateCardDto {
    return CreateCardDtoFromJSONTyped(json, false);
}

export function CreateCardDtoFromJSONTyped(json: any, ignoreDiscriminator: boolean): CreateCardDto {
    if (json == null) {
        return json;
    }
    return {
        
        'title': json['title'],
        'description': json['description'] == null ? undefined : json['description'],
        'priority': json['priority'] == null ? undefined : json['priority'],
        'type': json['type'] == null ? undefined : json['type'],
        'dueDate': json['dueDate'] == null ? undefined : (new Date(json['dueDate'])),
        'storyPoints': json['storyPoints'] == null ? undefined : json['storyPoints'],
        'assigneeId': json['assigneeId'] == null ? undefined : json['assigneeId'],
        'reporterId': json['reporterId'] == null ? undefined : json['reporterId'],
        'labelIds': json['labelIds'] == null ? undefined : json['labelIds'],
    };
}

export function CreateCardDtoToJSON(json: any): CreateCardDto {
    return CreateCardDtoToJSONTyped(json, false);
}

export function CreateCardDtoToJSONTyped(value?: CreateCardDto | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'title': value['title'],
        'description': value['description'],
        'priority': value['priority'],
        'type': value['type'],
        'dueDate': value['dueDate'] == null ? value['dueDate'] : value['dueDate'].toISOString(),
        'storyPoints': value['storyPoints'],
        'assigneeId': value['assigneeId'],
        'reporterId': value['reporterId'],
        'labelIds': value['labelIds'],
    };
}

