/* tslint:disable */
/* eslint-disable */
/**
 * Workboard API
 * Hybrid Trello / Jira board management API
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface UpdateBoardDto
 */
export interface UpdateBoardDto {
    /**
     * 
     * @type {string}
     * @memberof UpdateBoardDto
     */
    name?: string;
    /**
     * 
     * @type {string}
     * @memberof UpdateBoardDto
     */
    description?: string;
}

/**
 * Check if a given object implements the UpdateBoardDto interface.
 */
export function instanceOfUpdateBoardDto(value: object): value is UpdateBoardDto {
    return true;
}

export function UpdateBoardDtoFromJSON(json: any): UpdateBoardDto {
    return UpdateBoardDtoFromJSONTyped(json, false);
}

export function UpdateBoardDtoFromJSONTyped(json: any, ignoreDiscriminator: boolean): UpdateBoardDto {
    if (json == null) {
        return json;
    }
    return {
        
        'name': json['name'] == null ? undefined : json['name'],
        'description': json['description'] == null ? undefined : json['description'],
    };
}

export function UpdateBoardDtoToJSON(json: any): UpdateBoardDto {
    return UpdateBoardDtoToJSONTyped(json, false);
}

export function UpdateBoardDtoToJSONTyped(value?: UpdateBoardDto | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'name': value['name'],
        'description': value['description'],
    };
}

