/* tslint:disable */
/* eslint-disable */
/**
 * Workboard API
 * Hybrid Trello / Jira board management API
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface UpdateCardWatchersDto
 */
export interface UpdateCardWatchersDto {
    /**
     * Complete list of watcher user ids
     * @type {Array<string>}
     * @memberof UpdateCardWatchersDto
     */
    watcherIds: Array<string>;
}

/**
 * Check if a given object implements the UpdateCardWatchersDto interface.
 */
export function instanceOfUpdateCardWatchersDto(value: object): value is UpdateCardWatchersDto {
    if (!('watcherIds' in value) || value['watcherIds'] === undefined) return false;
    return true;
}

export function UpdateCardWatchersDtoFromJSON(json: any): UpdateCardWatchersDto {
    return UpdateCardWatchersDtoFromJSONTyped(json, false);
}

export function UpdateCardWatchersDtoFromJSONTyped(json: any, ignoreDiscriminator: boolean): UpdateCardWatchersDto {
    if (json == null) {
        return json;
    }
    return {
        
        'watcherIds': json['watcherIds'],
    };
}

export function UpdateCardWatchersDtoToJSON(json: any): UpdateCardWatchersDto {
    return UpdateCardWatchersDtoToJSONTyped(json, false);
}

export function UpdateCardWatchersDtoToJSONTyped(value?: UpdateCardWatchersDto | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'watcherIds': value['watcherIds'],
    };
}

