/* tslint:disable */
/* eslint-disable */
/**
 * Workboard API
 * Hybrid Trello / Jira board management API
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface UpdateUserRoleDto
 */
export interface UpdateUserRoleDto {
    /**
     * 
     * @type {string}
     * @memberof UpdateUserRoleDto
     */
    role: UpdateUserRoleDtoRoleEnum;
}


/**
 * @export
 */
export const UpdateUserRoleDtoRoleEnum = {
    Admin: 'ADMIN',
    User: 'USER'
} as const;
export type UpdateUserRoleDtoRoleEnum = typeof UpdateUserRoleDtoRoleEnum[keyof typeof UpdateUserRoleDtoRoleEnum];


/**
 * Check if a given object implements the UpdateUserRoleDto interface.
 */
export function instanceOfUpdateUserRoleDto(value: object): value is UpdateUserRoleDto {
    if (!('role' in value) || value['role'] === undefined) return false;
    return true;
}

export function UpdateUserRoleDtoFromJSON(json: any): UpdateUserRoleDto {
    return UpdateUserRoleDtoFromJSONTyped(json, false);
}

export function UpdateUserRoleDtoFromJSONTyped(json: any, ignoreDiscriminator: boolean): UpdateUserRoleDto {
    if (json == null) {
        return json;
    }
    return {
        
        'role': json['role'],
    };
}

export function UpdateUserRoleDtoToJSON(json: any): UpdateUserRoleDto {
    return UpdateUserRoleDtoToJSONTyped(json, false);
}

export function UpdateUserRoleDtoToJSONTyped(value?: UpdateUserRoleDto | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'role': value['role'],
    };
}

