/* tslint:disable */
/* eslint-disable */
/**
 * Workboard API
 * Hybrid Trello / Jira board management API
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface UpdateCardSprintDto
 */
export interface UpdateCardSprintDto {
    /**
     * Sprint identifier to link the card to. Omit to remove from sprint.
     * @type {string}
     * @memberof UpdateCardSprintDto
     */
    sprintId?: string;
}

/**
 * Check if a given object implements the UpdateCardSprintDto interface.
 */
export function instanceOfUpdateCardSprintDto(value: object): value is UpdateCardSprintDto {
    return true;
}

export function UpdateCardSprintDtoFromJSON(json: any): UpdateCardSprintDto {
    return UpdateCardSprintDtoFromJSONTyped(json, false);
}

export function UpdateCardSprintDtoFromJSONTyped(json: any, ignoreDiscriminator: boolean): UpdateCardSprintDto {
    if (json == null) {
        return json;
    }
    return {
        
        'sprintId': json['sprintId'] == null ? undefined : json['sprintId'],
    };
}

export function UpdateCardSprintDtoToJSON(json: any): UpdateCardSprintDto {
    return UpdateCardSprintDtoToJSONTyped(json, false);
}

export function UpdateCardSprintDtoToJSONTyped(value?: UpdateCardSprintDto | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'sprintId': value['sprintId'],
    };
}

