/* tslint:disable */
/* eslint-disable */
/**
 * Workboard API
 * Hybrid Trello / Jira board management API
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface UpdateColumnDto
 */
export interface UpdateColumnDto {
    /**
     * 
     * @type {string}
     * @memberof UpdateColumnDto
     */
    title?: string;
    /**
     * 
     * @type {number}
     * @memberof UpdateColumnDto
     */
    position?: number;
}

/**
 * Check if a given object implements the UpdateColumnDto interface.
 */
export function instanceOfUpdateColumnDto(value: object): value is UpdateColumnDto {
    return true;
}

export function UpdateColumnDtoFromJSON(json: any): UpdateColumnDto {
    return UpdateColumnDtoFromJSONTyped(json, false);
}

export function UpdateColumnDtoFromJSONTyped(json: any, ignoreDiscriminator: boolean): UpdateColumnDto {
    if (json == null) {
        return json;
    }
    return {
        
        'title': json['title'] == null ? undefined : json['title'],
        'position': json['position'] == null ? undefined : json['position'],
    };
}

export function UpdateColumnDtoToJSON(json: any): UpdateColumnDto {
    return UpdateColumnDtoToJSONTyped(json, false);
}

export function UpdateColumnDtoToJSONTyped(value?: UpdateColumnDto | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'title': value['title'],
        'position': value['position'],
    };
}

