// @ts-nocheck
/* tslint:disable */
/* eslint-disable */
/**
 * Workboard API
 * Hybrid Trello / Jira board management API
 *
 * The version of the OpenAPI document: 1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from "../runtime";
/**
 *
 * @export
 * @interface AddBoardMemberDto
 */
export interface AddBoardMemberDto {
  /**
   *
   * @type {string}
   * @memberof AddBoardMemberDto
   */
  userId?: string;
  /**
   *
   * @type {string}
   * @memberof AddBoardMemberDto
   */
  email?: string;
}

/**
 * Check if a given object implements the AddBoardMemberDto interface.
 */
export function instanceOfAddBoardMemberDto(
  value: object
): value is AddBoardMemberDto {
  return true;
}

export function AddBoardMemberDtoFromJSON(json: any): AddBoardMemberDto {
  return AddBoardMemberDtoFromJSONTyped(json, false);
}

export function AddBoardMemberDtoFromJSONTyped(
  json: any,
  ignoreDiscriminator: boolean
): AddBoardMemberDto {
  if (json == null) {
    return json;
  }
  return {
    userId: json["userId"] == null ? undefined : json["userId"],
    email: json["email"] == null ? undefined : json["email"]
  };
}

export function AddBoardMemberDtoToJSON(json: any): AddBoardMemberDto {
  return AddBoardMemberDtoToJSONTyped(json, false);
}

export function AddBoardMemberDtoToJSONTyped(
  value?: AddBoardMemberDto | null,
  ignoreDiscriminator: boolean = false
): any {
  if (value == null) {
    return value;
  }

  return {
    userId: value["userId"],
    email: value["email"]
  };
}
