// @ts-nocheck
/* tslint:disable */
/* eslint-disable */
/**
 * Workboard API
 * Hybrid Trello / Jira board management API
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface CreateLabelDto
 */
export interface CreateLabelDto {
    /**
     * 
     * @type {string}
     * @memberof CreateLabelDto
     */
    name: string;
    /**
     * 
     * @type {string}
     * @memberof CreateLabelDto
     */
    color: string;
}

/**
 * Check if a given object implements the CreateLabelDto interface.
 */
export function instanceOfCreateLabelDto(value: object): value is CreateLabelDto {
    if (!('name' in value) || value['name'] === undefined) return false;
    if (!('color' in value) || value['color'] === undefined) return false;
    return true;
}

export function CreateLabelDtoFromJSON(json: any): CreateLabelDto {
    return CreateLabelDtoFromJSONTyped(json, false);
}

export function CreateLabelDtoFromJSONTyped(json: any, ignoreDiscriminator: boolean): CreateLabelDto {
    if (json == null) {
        return json;
    }
    return {
        
        'name': json['name'],
        'color': json['color'],
    };
}

export function CreateLabelDtoToJSON(json: any): CreateLabelDto {
    return CreateLabelDtoToJSONTyped(json, false);
}

export function CreateLabelDtoToJSONTyped(value?: CreateLabelDto | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'name': value['name'],
        'color': value['color'],
    };
}

