/* tslint:disable */
/* eslint-disable */
/**
 * Workboard API
 * Hybrid Trello / Jira board management API
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface CreateSprintDto
 */
export interface CreateSprintDto {
    /**
     * 
     * @type {string}
     * @memberof CreateSprintDto
     */
    name: string;
    /**
     * 
     * @type {string}
     * @memberof CreateSprintDto
     */
    goal?: string;
    /**
     * 
     * @type {Date}
     * @memberof CreateSprintDto
     */
    startDate?: Date;
    /**
     * 
     * @type {Date}
     * @memberof CreateSprintDto
     */
    endDate?: Date;
}

/**
 * Check if a given object implements the CreateSprintDto interface.
 */
export function instanceOfCreateSprintDto(value: object): value is CreateSprintDto {
    if (!('name' in value) || value['name'] === undefined) return false;
    return true;
}

export function CreateSprintDtoFromJSON(json: any): CreateSprintDto {
    return CreateSprintDtoFromJSONTyped(json, false);
}

export function CreateSprintDtoFromJSONTyped(json: any, ignoreDiscriminator: boolean): CreateSprintDto {
    if (json == null) {
        return json;
    }
    return {
        
        'name': json['name'],
        'goal': json['goal'] == null ? undefined : json['goal'],
        'startDate': json['startDate'] == null ? undefined : (new Date(json['startDate'])),
        'endDate': json['endDate'] == null ? undefined : (new Date(json['endDate'])),
    };
}

export function CreateSprintDtoToJSON(json: any): CreateSprintDto {
    return CreateSprintDtoToJSONTyped(json, false);
}

export function CreateSprintDtoToJSONTyped(value?: CreateSprintDto | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'name': value['name'],
        'goal': value['goal'],
        'startDate': value['startDate'] == null ? value['startDate'] : value['startDate'].toISOString(),
        'endDate': value['endDate'] == null ? value['endDate'] : value['endDate'].toISOString(),
    };
}

