// @ts-nocheck
/* tslint:disable */
/* eslint-disable */
/**
 * Workboard API
 * Hybrid Trello / Jira board management API
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface CreateBoardDto
 */
export interface CreateBoardDto {
    /**
     * 
     * @type {string}
     * @memberof CreateBoardDto
     */
    name: string;
    /**
     * 
     * @type {string}
     * @memberof CreateBoardDto
     */
    description?: string;
}

/**
 * Check if a given object implements the CreateBoardDto interface.
 */
export function instanceOfCreateBoardDto(value: object): value is CreateBoardDto {
    if (!('name' in value) || value['name'] === undefined) return false;
    return true;
}

export function CreateBoardDtoFromJSON(json: any): CreateBoardDto {
    return CreateBoardDtoFromJSONTyped(json, false);
}

export function CreateBoardDtoFromJSONTyped(json: any, ignoreDiscriminator: boolean): CreateBoardDto {
    if (json == null) {
        return json;
    }
    return {
        
        'name': json['name'],
        'description': json['description'] == null ? undefined : json['description'],
    };
}

export function CreateBoardDtoToJSON(json: any): CreateBoardDto {
    return CreateBoardDtoToJSONTyped(json, false);
}

export function CreateBoardDtoToJSONTyped(value?: CreateBoardDto | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'name': value['name'],
        'description': value['description'],
    };
}

