/* tslint:disable */
/* eslint-disable */
/**
 * Workboard API
 * Hybrid Trello / Jira board management API
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface CreateColumnDto
 */
export interface CreateColumnDto {
    /**
     * 
     * @type {string}
     * @memberof CreateColumnDto
     */
    title: string;
    /**
     * 
     * @type {number}
     * @memberof CreateColumnDto
     */
    position?: number;
}

/**
 * Check if a given object implements the CreateColumnDto interface.
 */
export function instanceOfCreateColumnDto(value: object): value is CreateColumnDto {
    if (!('title' in value) || value['title'] === undefined) return false;
    return true;
}

export function CreateColumnDtoFromJSON(json: any): CreateColumnDto {
    return CreateColumnDtoFromJSONTyped(json, false);
}

export function CreateColumnDtoFromJSONTyped(json: any, ignoreDiscriminator: boolean): CreateColumnDto {
    if (json == null) {
        return json;
    }
    return {
        
        'title': json['title'],
        'position': json['position'] == null ? undefined : json['position'],
    };
}

export function CreateColumnDtoToJSON(json: any): CreateColumnDto {
    return CreateColumnDtoToJSONTyped(json, false);
}

export function CreateColumnDtoToJSONTyped(value?: CreateColumnDto | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'title': value['title'],
        'position': value['position'],
    };
}

