// @ts-nocheck
/* tslint:disable */
/* eslint-disable */
/**
 * Workboard API
 * Hybrid Trello / Jira board management API
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface MoveCardDto
 */
export interface MoveCardDto {
    /**
     * 
     * @type {string}
     * @memberof MoveCardDto
     */
    targetColumnId: string;
    /**
     * New zero-based index within the target column
     * @type {number}
     * @memberof MoveCardDto
     */
    targetPosition?: number;
}

/**
 * Check if a given object implements the MoveCardDto interface.
 */
export function instanceOfMoveCardDto(value: object): value is MoveCardDto {
    if (!('targetColumnId' in value) || value['targetColumnId'] === undefined) return false;
    return true;
}

export function MoveCardDtoFromJSON(json: any): MoveCardDto {
    return MoveCardDtoFromJSONTyped(json, false);
}

export function MoveCardDtoFromJSONTyped(json: any, ignoreDiscriminator: boolean): MoveCardDto {
    if (json == null) {
        return json;
    }
    return {
        
        'targetColumnId': json['targetColumnId'],
        'targetPosition': json['targetPosition'] == null ? undefined : json['targetPosition'],
    };
}

export function MoveCardDtoToJSON(json: any): MoveCardDto {
    return MoveCardDtoToJSONTyped(json, false);
}

export function MoveCardDtoToJSONTyped(value?: MoveCardDto | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'targetColumnId': value['targetColumnId'],
        'targetPosition': value['targetPosition'],
    };
}

