// @ts-nocheck
/* tslint:disable */
/* eslint-disable */
/**
 * Workboard API
 * Hybrid Trello / Jira board management API
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface RegisterDto
 */
export interface RegisterDto {
    /**
     * 
     * @type {string}
     * @memberof RegisterDto
     */
    email: string;
    /**
     * 
     * @type {string}
     * @memberof RegisterDto
     */
    password: string;
    /**
     * 
     * @type {string}
     * @memberof RegisterDto
     */
    displayName: string;
    /**
     * 
     * @type {string}
     * @memberof RegisterDto
     */
    role?: RegisterDtoRoleEnum;
}


/**
 * @export
 */
export const RegisterDtoRoleEnum = {
    Admin: 'ADMIN',
    User: 'USER'
} as const;
export type RegisterDtoRoleEnum = typeof RegisterDtoRoleEnum[keyof typeof RegisterDtoRoleEnum];


/**
 * Check if a given object implements the RegisterDto interface.
 */
export function instanceOfRegisterDto(value: object): value is RegisterDto {
    if (!('email' in value) || value['email'] === undefined) return false;
    if (!('password' in value) || value['password'] === undefined) return false;
    if (!('displayName' in value) || value['displayName'] === undefined) return false;
    return true;
}

export function RegisterDtoFromJSON(json: any): RegisterDto {
    return RegisterDtoFromJSONTyped(json, false);
}

export function RegisterDtoFromJSONTyped(json: any, ignoreDiscriminator: boolean): RegisterDto {
    if (json == null) {
        return json;
    }
    return {
        
        'email': json['email'],
        'password': json['password'],
        'displayName': json['displayName'],
        'role': json['role'] == null ? undefined : json['role'],
    };
}

export function RegisterDtoToJSON(json: any): RegisterDto {
    return RegisterDtoToJSONTyped(json, false);
}

export function RegisterDtoToJSONTyped(value?: RegisterDto | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'email': value['email'],
        'password': value['password'],
        'displayName': value['displayName'],
        'role': value['role'],
    };
}

