// @ts-nocheck
/* tslint:disable */
/* eslint-disable */
/**
 * Workboard API
 * Hybrid Trello / Jira board management API
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface ReorderColumnsDto
 */
export interface ReorderColumnsDto {
    /**
     * Ordered list of column identifiers
     * @type {Array<string>}
     * @memberof ReorderColumnsDto
     */
    columnOrder: Array<string>;
}

/**
 * Check if a given object implements the ReorderColumnsDto interface.
 */
export function instanceOfReorderColumnsDto(value: object): value is ReorderColumnsDto {
    if (!('columnOrder' in value) || value['columnOrder'] === undefined) return false;
    return true;
}

export function ReorderColumnsDtoFromJSON(json: any): ReorderColumnsDto {
    return ReorderColumnsDtoFromJSONTyped(json, false);
}

export function ReorderColumnsDtoFromJSONTyped(json: any, ignoreDiscriminator: boolean): ReorderColumnsDto {
    if (json == null) {
        return json;
    }
    return {
        
        'columnOrder': json['columnOrder'],
    };
}

export function ReorderColumnsDtoToJSON(json: any): ReorderColumnsDto {
    return ReorderColumnsDtoToJSONTyped(json, false);
}

export function ReorderColumnsDtoToJSONTyped(value?: ReorderColumnsDto | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'columnOrder': value['columnOrder'],
    };
}

