// @ts-nocheck
/* tslint:disable */
/* eslint-disable */
/**
 * Workboard API
 * Hybrid Trello / Jira board management API
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface UpdateSprintStatusDto
 */
export interface UpdateSprintStatusDto {
    /**
     * 
     * @type {string}
     * @memberof UpdateSprintStatusDto
     */
    status: UpdateSprintStatusDtoStatusEnum;
}


/**
 * @export
 */
export const UpdateSprintStatusDtoStatusEnum = {
    Planned: 'PLANNED',
    Active: 'ACTIVE',
    Completed: 'COMPLETED',
    Cancelled: 'CANCELLED'
} as const;
export type UpdateSprintStatusDtoStatusEnum = typeof UpdateSprintStatusDtoStatusEnum[keyof typeof UpdateSprintStatusDtoStatusEnum];


/**
 * Check if a given object implements the UpdateSprintStatusDto interface.
 */
export function instanceOfUpdateSprintStatusDto(value: object): value is UpdateSprintStatusDto {
    if (!('status' in value) || value['status'] === undefined) return false;
    return true;
}

export function UpdateSprintStatusDtoFromJSON(json: any): UpdateSprintStatusDto {
    return UpdateSprintStatusDtoFromJSONTyped(json, false);
}

export function UpdateSprintStatusDtoFromJSONTyped(json: any, ignoreDiscriminator: boolean): UpdateSprintStatusDto {
    if (json == null) {
        return json;
    }
    return {
        
        'status': json['status'],
    };
}

export function UpdateSprintStatusDtoToJSON(json: any): UpdateSprintStatusDto {
    return UpdateSprintStatusDtoToJSONTyped(json, false);
}

export function UpdateSprintStatusDtoToJSONTyped(value?: UpdateSprintStatusDto | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'status': value['status'],
    };
}

