/* tslint:disable */
/* eslint-disable */
/**
 * Workboard API
 * Hybrid Trello / Jira board management API
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface UpdateLabelDto
 */
export interface UpdateLabelDto {
    /**
     * 
     * @type {string}
     * @memberof UpdateLabelDto
     */
    name?: string;
    /**
     * 
     * @type {string}
     * @memberof UpdateLabelDto
     */
    color?: string;
}

/**
 * Check if a given object implements the UpdateLabelDto interface.
 */
export function instanceOfUpdateLabelDto(value: object): value is UpdateLabelDto {
    return true;
}

export function UpdateLabelDtoFromJSON(json: any): UpdateLabelDto {
    return UpdateLabelDtoFromJSONTyped(json, false);
}

export function UpdateLabelDtoFromJSONTyped(json: any, ignoreDiscriminator: boolean): UpdateLabelDto {
    if (json == null) {
        return json;
    }
    return {
        
        'name': json['name'] == null ? undefined : json['name'],
        'color': json['color'] == null ? undefined : json['color'],
    };
}

export function UpdateLabelDtoToJSON(json: any): UpdateLabelDto {
    return UpdateLabelDtoToJSONTyped(json, false);
}

export function UpdateLabelDtoToJSONTyped(value?: UpdateLabelDto | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'name': value['name'],
        'color': value['color'],
    };
}

