// @ts-nocheck
/* tslint:disable */
/* eslint-disable */
/**
 * Workboard API
 * Hybrid Trello / Jira board management API
 *
 * The version of the OpenAPI document: 1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from "../runtime";
/**
 *
 * @export
 * @interface UpdateCommentDto
 */
export interface UpdateCommentDto {
  /**
   *
   * @type {string}
   * @memberof UpdateCommentDto
   */
  content: string;
}

/**
 * Check if a given object implements the UpdateCommentDto interface.
 */
export function instanceOfUpdateCommentDto(
  value: object
): value is UpdateCommentDto {
  if (!("content" in value) || value["content"] === undefined) return false;
  return true;
}

export function UpdateCommentDtoFromJSON(json: any): UpdateCommentDto {
  return UpdateCommentDtoFromJSONTyped(json, false);
}

export function UpdateCommentDtoFromJSONTyped(
  json: any,
  ignoreDiscriminator: boolean
): UpdateCommentDto {
  if (json == null) {
    return json;
  }
  return {
    content: json["content"]
  };
}

export function UpdateCommentDtoToJSON(json: any): UpdateCommentDto {
  return UpdateCommentDtoToJSONTyped(json, false);
}

export function UpdateCommentDtoToJSONTyped(
  value?: UpdateCommentDto | null,
  ignoreDiscriminator: boolean = false
): any {
  if (value == null) {
    return value;
  }

  return {
    content: value["content"]
  };
}
