// @ts-nocheck
/* tslint:disable */
/* eslint-disable */
/**
 * Workboard API
 * Hybrid Trello / Jira board management API
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface UpdateSprintDto
 */
export interface UpdateSprintDto {
    /**
     * 
     * @type {string}
     * @memberof UpdateSprintDto
     */
    name?: string;
    /**
     * 
     * @type {string}
     * @memberof UpdateSprintDto
     */
    goal?: string;
    /**
     * 
     * @type {Date}
     * @memberof UpdateSprintDto
     */
    startDate?: Date;
    /**
     * 
     * @type {Date}
     * @memberof UpdateSprintDto
     */
    endDate?: Date;
}

/**
 * Check if a given object implements the UpdateSprintDto interface.
 */
export function instanceOfUpdateSprintDto(value: object): value is UpdateSprintDto {
    return true;
}

export function UpdateSprintDtoFromJSON(json: any): UpdateSprintDto {
    return UpdateSprintDtoFromJSONTyped(json, false);
}

export function UpdateSprintDtoFromJSONTyped(json: any, ignoreDiscriminator: boolean): UpdateSprintDto {
    if (json == null) {
        return json;
    }
    return {
        
        'name': json['name'] == null ? undefined : json['name'],
        'goal': json['goal'] == null ? undefined : json['goal'],
        'startDate': json['startDate'] == null ? undefined : (new Date(json['startDate'])),
        'endDate': json['endDate'] == null ? undefined : (new Date(json['endDate'])),
    };
}

export function UpdateSprintDtoToJSON(json: any): UpdateSprintDto {
    return UpdateSprintDtoToJSONTyped(json, false);
}

export function UpdateSprintDtoToJSONTyped(value?: UpdateSprintDto | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'name': value['name'],
        'goal': value['goal'],
        'startDate': value['startDate'] == null ? value['startDate'] : value['startDate'].toISOString(),
        'endDate': value['endDate'] == null ? value['endDate'] : value['endDate'].toISOString(),
    };
}

