// @ts-nocheck
/* tslint:disable */
/* eslint-disable */
/**
 * Workboard API
 * Hybrid Trello / Jira board management API
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface UpdateCardDto
 */
export interface UpdateCardDto {
    /**
     * 
     * @type {string}
     * @memberof UpdateCardDto
     */
    title?: string;
    /**
     * 
     * @type {string}
     * @memberof UpdateCardDto
     */
    description?: string;
    /**
     * 
     * @type {string}
     * @memberof UpdateCardDto
     */
    priority?: UpdateCardDtoPriorityEnum;
    /**
     * 
     * @type {string}
     * @memberof UpdateCardDto
     */
    type?: UpdateCardDtoTypeEnum;
    /**
     * 
     * @type {Date}
     * @memberof UpdateCardDto
     */
    dueDate?: Date;
    /**
     * 
     * @type {number}
     * @memberof UpdateCardDto
     */
    storyPoints?: number;
    /**
     * 
     * @type {string}
     * @memberof UpdateCardDto
     */
    assigneeId?: string;
    /**
     * 
     * @type {string}
     * @memberof UpdateCardDto
     */
    reporterId?: string;
    /**
     * Associated label identifiers
     * @type {Array<string>}
     * @memberof UpdateCardDto
     */
    labelIds?: Array<string>;
}


/**
 * @export
 */
export const UpdateCardDtoPriorityEnum = {
    Low: 'LOW',
    Medium: 'MEDIUM',
    High: 'HIGH',
    Critical: 'CRITICAL'
} as const;
export type UpdateCardDtoPriorityEnum = typeof UpdateCardDtoPriorityEnum[keyof typeof UpdateCardDtoPriorityEnum];

/**
 * @export
 */
export const UpdateCardDtoTypeEnum = {
    Task: 'TASK',
    Bug: 'BUG',
    Story: 'STORY',
    Epic: 'EPIC'
} as const;
export type UpdateCardDtoTypeEnum = typeof UpdateCardDtoTypeEnum[keyof typeof UpdateCardDtoTypeEnum];


/**
 * Check if a given object implements the UpdateCardDto interface.
 */
export function instanceOfUpdateCardDto(value: object): value is UpdateCardDto {
    return true;
}

export function UpdateCardDtoFromJSON(json: any): UpdateCardDto {
    return UpdateCardDtoFromJSONTyped(json, false);
}

export function UpdateCardDtoFromJSONTyped(json: any, ignoreDiscriminator: boolean): UpdateCardDto {
    if (json == null) {
        return json;
    }
    return {
        
        'title': json['title'] == null ? undefined : json['title'],
        'description': json['description'] == null ? undefined : json['description'],
        'priority': json['priority'] == null ? undefined : json['priority'],
        'type': json['type'] == null ? undefined : json['type'],
        'dueDate': json['dueDate'] == null ? undefined : (new Date(json['dueDate'])),
        'storyPoints': json['storyPoints'] == null ? undefined : json['storyPoints'],
        'assigneeId': json['assigneeId'] == null ? undefined : json['assigneeId'],
        'reporterId': json['reporterId'] == null ? undefined : json['reporterId'],
        'labelIds': json['labelIds'] == null ? undefined : json['labelIds'],
    };
}

export function UpdateCardDtoToJSON(json: any): UpdateCardDto {
    return UpdateCardDtoToJSONTyped(json, false);
}

export function UpdateCardDtoToJSONTyped(value?: UpdateCardDto | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'title': value['title'],
        'description': value['description'],
        'priority': value['priority'],
        'type': value['type'],
        'dueDate': value['dueDate'] == null ? value['dueDate'] : value['dueDate'].toISOString(),
        'storyPoints': value['storyPoints'],
        'assigneeId': value['assigneeId'],
        'reporterId': value['reporterId'],
        'labelIds': value['labelIds'],
    };
}

