// @ts-nocheck
/* tslint:disable */
/* eslint-disable */
/**
 * Workboard API
 * Hybrid Trello / Jira board management API
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface UpdateCardLabelsDto
 */
export interface UpdateCardLabelsDto {
    /**
     * Complete list of label ids applied to the card
     * @type {Array<string>}
     * @memberof UpdateCardLabelsDto
     */
    labelIds: Array<string>;
}

/**
 * Check if a given object implements the UpdateCardLabelsDto interface.
 */
export function instanceOfUpdateCardLabelsDto(value: object): value is UpdateCardLabelsDto {
    if (!('labelIds' in value) || value['labelIds'] === undefined) return false;
    return true;
}

export function UpdateCardLabelsDtoFromJSON(json: any): UpdateCardLabelsDto {
    return UpdateCardLabelsDtoFromJSONTyped(json, false);
}

export function UpdateCardLabelsDtoFromJSONTyped(json: any, ignoreDiscriminator: boolean): UpdateCardLabelsDto {
    if (json == null) {
        return json;
    }
    return {
        
        'labelIds': json['labelIds'],
    };
}

export function UpdateCardLabelsDtoToJSON(json: any): UpdateCardLabelsDto {
    return UpdateCardLabelsDtoToJSONTyped(json, false);
}

export function UpdateCardLabelsDtoToJSONTyped(value?: UpdateCardLabelsDto | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'labelIds': value['labelIds'],
    };
}

