// @ts-nocheck
/* tslint:disable */
/* eslint-disable */
/**
 * Workboard API
 * Hybrid Trello / Jira board management API
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface UpdateChecklistItemDto
 */
export interface UpdateChecklistItemDto {
    /**
     * 
     * @type {string}
     * @memberof UpdateChecklistItemDto
     */
    content?: string;
    /**
     * 
     * @type {boolean}
     * @memberof UpdateChecklistItemDto
     */
    completed?: boolean;
    /**
     * 
     * @type {number}
     * @memberof UpdateChecklistItemDto
     */
    position?: number;
}

/**
 * Check if a given object implements the UpdateChecklistItemDto interface.
 */
export function instanceOfUpdateChecklistItemDto(value: object): value is UpdateChecklistItemDto {
    return true;
}

export function UpdateChecklistItemDtoFromJSON(json: any): UpdateChecklistItemDto {
    return UpdateChecklistItemDtoFromJSONTyped(json, false);
}

export function UpdateChecklistItemDtoFromJSONTyped(json: any, ignoreDiscriminator: boolean): UpdateChecklistItemDto {
    if (json == null) {
        return json;
    }
    return {
        
        'content': json['content'] == null ? undefined : json['content'],
        'completed': json['completed'] == null ? undefined : json['completed'],
        'position': json['position'] == null ? undefined : json['position'],
    };
}

export function UpdateChecklistItemDtoToJSON(json: any): UpdateChecklistItemDto {
    return UpdateChecklistItemDtoToJSONTyped(json, false);
}

export function UpdateChecklistItemDtoToJSONTyped(value?: UpdateChecklistItemDto | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'content': value['content'],
        'completed': value['completed'],
        'position': value['position'],
    };
}

