// @ts-nocheck
/* tslint:disable */
/* eslint-disable */
/**
 * Workboard API
 * Hybrid Trello / Jira board management API
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface UpdateCardAssigneeDto
 */
export interface UpdateCardAssigneeDto {
    /**
     * Leave empty to unassign
     * @type {string}
     * @memberof UpdateCardAssigneeDto
     */
    assigneeId?: string;
}

/**
 * Check if a given object implements the UpdateCardAssigneeDto interface.
 */
export function instanceOfUpdateCardAssigneeDto(value: object): value is UpdateCardAssigneeDto {
    return true;
}

export function UpdateCardAssigneeDtoFromJSON(json: any): UpdateCardAssigneeDto {
    return UpdateCardAssigneeDtoFromJSONTyped(json, false);
}

export function UpdateCardAssigneeDtoFromJSONTyped(json: any, ignoreDiscriminator: boolean): UpdateCardAssigneeDto {
    if (json == null) {
        return json;
    }
    return {
        
        'assigneeId': json['assigneeId'] == null ? undefined : json['assigneeId'],
    };
}

export function UpdateCardAssigneeDtoToJSON(json: any): UpdateCardAssigneeDto {
    return UpdateCardAssigneeDtoToJSONTyped(json, false);
}

export function UpdateCardAssigneeDtoToJSONTyped(value?: UpdateCardAssigneeDto | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'assigneeId': value['assigneeId'],
    };
}

